logF: 'experiments/'
refF: 'data/train.mono.1.de-en.de'
use_mono: True
epoch: 50
batch_size: 4
optim: 'adam'
cell: 'lstm'
attention: 'bahdanau'
learning_rate: 0.001
max_grad_norm: 1
learning_rate_decay: 0.5
start_decay_at: 8
emb_size: 300
hidden_size: 16
dec_num_layers: 1
enc_num_layers: 1
res_layers: 1
bidirectional: True
dropout: 0.15
max_time_step: 50
eval_interval: 5
save_interval: 1000
metrics: ['bleu']
shared_vocab: False
beam_size: 5
unk: False
schedule: True
resRNN: False
selfatt: False
attemb: False
hops: 3
schesamp: False
length_norm: True
emb: fasttext2
src_emb_file_path: data/fasttext/cc.de.300.vec
tgt_emb_file_path: data/fasttext/cc.en.300.vec