logF: 'data/'
refF: 'data/es-en/test.src-tgt.tgt'
use_mono: False
use_label_loss: False
test_on_mono: False
epoch: 50
batch_size: 32
optim: 'adam'
cell: 'lstm'
attention: 'bahdanau'
learning_rate: 0.001
max_grad_norm: 1
learning_rate_decay: 0.5
start_decay_at: 8
emb_size: 256
hidden_size: 256
dec_num_layers: 1
enc_num_layers: 1
res_layers: 1
bidirectional: True
dropout: 0.15
max_time_step: 50
eval_interval: 500
save_interval: 1000
metrics: ['bleu']
shared_vocab: False
beam_size: 1
unk: False
schedule: True
resRNN: False
selfatt: False
attemb: False
hops: 3
schesamp: False
length_norm: True
emb: no_fasttext

