data: 'data/de-en_save'
mono_data: 'data/de-en_save_mono'
logF: 'experiments/'
refF: 'nist08.tok.ref'
use_mono: True
epoch: 50
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.0003
max_grad_norm: 1
learning_rate_decay: 0.5
start_decay_at: 8
emb_size: 512
hidden_size: 512
dec_num_layers: 2
enc_num_layers: 3
res_layers: 1
bidirectional: True
dropout: 0.15
max_time_step: 50
eval_interval: 5000
save_interval: 1000
metrics: ['bleu']
shared_vocab: False
beam_size: 5
unk: False
schedule: True
resRNN: False
selfatt: False
attemb: False
hops: 3
schesamp: False
length_norm: True
